/****************************************************************************************************/
/* Information
File: pdgamemodetypes.h
Author: headers.sh
This file was autogenerated by headers.sh. It contains an enumerated type called PDGamemodeType.
The script looks at files matching the pattern *Gamemode.h in /home/john/programming/C++/simpleLevel/src/headers/gamemodes and makes
enumerations of the form PDGM_* */
/****************************************************************************************************/
#ifndef PDGAMEMODETYPES_H_INCLUDED
#define PDGAMEMODETYPES_H_INCLUDED

#include <string>

enum PDGamemodeType {
	PDGM_Splash,
	PDGM_Invalid
};

inline PDGamemodeType StringToPDGamemodeType(const std::string& str) {
if (str == "Splash") return PDGM_Splash;

return PDGM_Invalid;
}
#endif /* PDGAMEMODETYPES_H_INCLUDED */
