/****************************************************************************************************/
/* Information
File: registerpdgamemodetypes.h
Author: headers.sh
This file was autogenerated by headers.sh. It looks for files that match
the pattern *Gamemode.h in /home/john/programming/C++/simpleLevel/src/headers/gamemodes
and registers different gamemode builders with the gamemode manager. */
/****************************************************************************************************/
#ifndef REGISTERPDGAMEMODETYPES_H_INCLUDED
#define REGISTERPDGAMEMODETYPES_H_INCLUDED

#include "pdgamemodemanager.h"
#include "SplashGamemode.h"

inline void RegisterGamemodes() {
	PDGamemodeManager::AddGamemode(PDGM_Splash, new PDGamemodeTBuilder<PDSplashGamemode>());
}

#endif /* REGISTERPDGAMEMODETYPES_H_INCLUDED */
