/****************************************************************************************************/
/* Information
File: pdcommandtype.h
Author: headers.sh
This file was autogenerated by headers.sh. It contains an enumerated type called PDCommandType.
The script looks at files matching the pattern *cmd.h in /home/john/programming/C++/simpleLevel/src/headers/commands and makes
enumerations of the form PDCmd_* */
/****************************************************************************************************/
#ifndef PDCOMMANDTYPE_H_INCLUDED
#define PDCOMMANDTYPE_H_INCLUDED

#include <string>

enum PDCommandType {
	PDCmd_Exit,
	PDCmd_Invalid
};

inline PDCommandType StringToPDCommandType(const std::string& str) {
if (str == "Exit") return PDCmd_Exit;

return PDCmd_Invalid;
}
#endif /* PDCOMMANDTYPE_H_INCLUDED */
