/****************************************************************************************************/
/* Information:
File: registerpdcommandtypes.h
Author: headers.sh
This file was generated by a script that looks at files ending in *cmd.h in
/home/john/programming/C++/simpleLevel/src/headers/commands 
and registers commands with the object manager. */
/****************************************************************************************************/
#ifndef REGISTERPDCOMMANDTYPES_H_INCLUDED
#define REGISTERPDCOMMANDTYPES_H_INCLUDED

#include "pdmanager.h"
#include "pdcommandbuilder.h"
#include "pdcommand.h"
#include "pdcommandtype.h"
#include "exitcmd.h"

inline void RegisterCommands() {
 PDObjectManager::AddCommand(PDCmd_Exit, new PDCommandTBuilder<ExitCmd>);
}
#endif /* REGISTERPDCOMMANDTYPES_H_INCLUDED */
