/****************************************************************************************************/
/* Information
File: registerpdcomponenttypes.h
Author: headers.sh
This file was autogenerated by headers.sh. It looks for files that match
the pattern *Component.h in /home/john/programming/C++/simpleLevel/src/headers/components
and registers different component builders with the object manager. */
/****************************************************************************************************/
#ifndef REGISTERPDCOMPONENTTYPES_H_INCLUDED
#define REGISTERPDCOMPONENTTYPES_H_INCLUDED

#include "pdcomponentbuilder.h"
#include "FadeComponent.h"
#include "GfxComponent.h"

inline void RegisterComponents() {
	PDObjectManager::AddComponent(PDC_Fade, new PDComponentTBuilder<PDFadeComponent>());
	PDObjectManager::AddComponent(PDC_Gfx, new PDComponentTBuilder<PDGfxComponent>());
}

#endif /* REGISTERPDCOMPONENTTYPES_H_INCLUDED */
