.mso pd.tmac
\" start manual page
.TH PDIniFile 7 11/21/19 "" "Project Dewpsi Development Manual"
.SH NAME
PDIniFile \- class that reads and parses INI files
.
.SH DESCRIPTION
.PP
.B PDIniFile
is a C++ class that implements reading of ini files. \c
There are only two public functions, \c
.BR ReadFile " and " SetToSection .
.
.IP
.B menubutton.ini
.EX
posx = 0
posy = 0
velx = 0
vely = 0
components = GfxComponent MouseInputComponent

[GfxComponent]
texture = temp.png
drawspace = hud

[MouseInputComponent]
bbox = 3 2 10 10
.EE
.
.PP
.
.SS "Class Methods"
.FA void ReadFile "const std::string&" file
Reads
.I file
and reads it into memory as an ini file.
.
.FA void SetToSection "const std::string&" sec
Goes to the section \fIsec\fP in the ini file.
.FA "template<typename T> void" GetValue "const std::string&" key T& val
Reads \c
.I key \c
in the currently marked section of an ini file and gives the result to \c
.IR val , \c
which can be of any type that can accept the extracted value.
